/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MaintenanceInfo;
import io.swagger.client.model.Metadata;
import io.swagger.client.model.Schemas;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Plan
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-26T00:20:45.219674+05:30[Asia/Kolkata]")
public class Plan {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("metadata")
  private Metadata metadata = null;

  @SerializedName("maintenance_info")
  private MaintenanceInfo maintenanceInfo = null;

  @SerializedName("free")
  private Boolean free = true;

  @SerializedName("bindable")
  private Boolean bindable = null;

  @SerializedName("schemas")
  private Schemas schemas = null;

  @SerializedName("maximum_polling_duration")
  private Integer maximumPollingDuration = null;

  @SerializedName("plan_updateable")
  private Boolean planUpdateable = null;

  @SerializedName("binding_rotatable")
  private Boolean bindingRotatable = false;

  public Plan id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Plan name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Plan description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Plan metadata(Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(description = "")
  public Metadata getMetadata() {
    return metadata;
  }

  public void setMetadata(Metadata metadata) {
    this.metadata = metadata;
  }

  public Plan maintenanceInfo(MaintenanceInfo maintenanceInfo) {
    this.maintenanceInfo = maintenanceInfo;
    return this;
  }

   /**
   * Get maintenanceInfo
   * @return maintenanceInfo
  **/
  @Schema(description = "")
  public MaintenanceInfo getMaintenanceInfo() {
    return maintenanceInfo;
  }

  public void setMaintenanceInfo(MaintenanceInfo maintenanceInfo) {
    this.maintenanceInfo = maintenanceInfo;
  }

  public Plan free(Boolean free) {
    this.free = free;
    return this;
  }

   /**
   * Get free
   * @return free
  **/
  @Schema(description = "")
  public Boolean isFree() {
    return free;
  }

  public void setFree(Boolean free) {
    this.free = free;
  }

  public Plan bindable(Boolean bindable) {
    this.bindable = bindable;
    return this;
  }

   /**
   * Get bindable
   * @return bindable
  **/
  @Schema(description = "")
  public Boolean isBindable() {
    return bindable;
  }

  public void setBindable(Boolean bindable) {
    this.bindable = bindable;
  }

  public Plan schemas(Schemas schemas) {
    this.schemas = schemas;
    return this;
  }

   /**
   * Get schemas
   * @return schemas
  **/
  @Schema(description = "")
  public Schemas getSchemas() {
    return schemas;
  }

  public void setSchemas(Schemas schemas) {
    this.schemas = schemas;
  }

  public Plan maximumPollingDuration(Integer maximumPollingDuration) {
    this.maximumPollingDuration = maximumPollingDuration;
    return this;
  }

   /**
   * Get maximumPollingDuration
   * @return maximumPollingDuration
  **/
  @Schema(description = "")
  public Integer getMaximumPollingDuration() {
    return maximumPollingDuration;
  }

  public void setMaximumPollingDuration(Integer maximumPollingDuration) {
    this.maximumPollingDuration = maximumPollingDuration;
  }

  public Plan planUpdateable(Boolean planUpdateable) {
    this.planUpdateable = planUpdateable;
    return this;
  }

   /**
   * Get planUpdateable
   * @return planUpdateable
  **/
  @Schema(description = "")
  public Boolean isPlanUpdateable() {
    return planUpdateable;
  }

  public void setPlanUpdateable(Boolean planUpdateable) {
    this.planUpdateable = planUpdateable;
  }

  public Plan bindingRotatable(Boolean bindingRotatable) {
    this.bindingRotatable = bindingRotatable;
    return this;
  }

   /**
   * Get bindingRotatable
   * @return bindingRotatable
  **/
  @Schema(description = "")
  public Boolean isBindingRotatable() {
    return bindingRotatable;
  }

  public void setBindingRotatable(Boolean bindingRotatable) {
    this.bindingRotatable = bindingRotatable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plan plan = (Plan) o;
    return Objects.equals(this.id, plan.id) &&
        Objects.equals(this.name, plan.name) &&
        Objects.equals(this.description, plan.description) &&
        Objects.equals(this.metadata, plan.metadata) &&
        Objects.equals(this.maintenanceInfo, plan.maintenanceInfo) &&
        Objects.equals(this.free, plan.free) &&
        Objects.equals(this.bindable, plan.bindable) &&
        Objects.equals(this.schemas, plan.schemas) &&
        Objects.equals(this.maximumPollingDuration, plan.maximumPollingDuration) &&
        Objects.equals(this.planUpdateable, plan.planUpdateable) &&
        Objects.equals(this.bindingRotatable, plan.bindingRotatable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, metadata, maintenanceInfo, free, bindable, schemas, maximumPollingDuration, planUpdateable, bindingRotatable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plan {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    maintenanceInfo: ").append(toIndentedString(maintenanceInfo)).append("\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    bindable: ").append(toIndentedString(bindable)).append("\n");
    sb.append("    schemas: ").append(toIndentedString(schemas)).append("\n");
    sb.append("    maximumPollingDuration: ").append(toIndentedString(maximumPollingDuration)).append("\n");
    sb.append("    planUpdateable: ").append(toIndentedString(planUpdateable)).append("\n");
    sb.append("    bindingRotatable: ").append(toIndentedString(bindingRotatable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
