/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Context;
import io.swagger.client.model.ServiceInstancePreviousValues;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ServiceInstanceUpdateRequestBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-26T00:20:45.219674+05:30[Asia/Kolkata]")
public class ServiceInstanceUpdateRequestBody {
  @SerializedName("context")
  private Context context = null;

  @SerializedName("service_id")
  private String serviceId = null;

  @SerializedName("plan_id")
  private String planId = null;

  @SerializedName("parameters")
  private Object parameters = null;

  @SerializedName("previous_values")
  private ServiceInstancePreviousValues previousValues = null;

  public ServiceInstanceUpdateRequestBody context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }

  public ServiceInstanceUpdateRequestBody serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @Schema(required = true, description = "")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public ServiceInstanceUpdateRequestBody planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(description = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public ServiceInstanceUpdateRequestBody parameters(Object parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @Schema(description = "")
  public Object getParameters() {
    return parameters;
  }

  public void setParameters(Object parameters) {
    this.parameters = parameters;
  }

  public ServiceInstanceUpdateRequestBody previousValues(ServiceInstancePreviousValues previousValues) {
    this.previousValues = previousValues;
    return this;
  }

   /**
   * Get previousValues
   * @return previousValues
  **/
  @Schema(description = "")
  public ServiceInstancePreviousValues getPreviousValues() {
    return previousValues;
  }

  public void setPreviousValues(ServiceInstancePreviousValues previousValues) {
    this.previousValues = previousValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInstanceUpdateRequestBody serviceInstanceUpdateRequestBody = (ServiceInstanceUpdateRequestBody) o;
    return Objects.equals(this.context, serviceInstanceUpdateRequestBody.context) &&
        Objects.equals(this.serviceId, serviceInstanceUpdateRequestBody.serviceId) &&
        Objects.equals(this.planId, serviceInstanceUpdateRequestBody.planId) &&
        Objects.equals(this.parameters, serviceInstanceUpdateRequestBody.parameters) &&
        Objects.equals(this.previousValues, serviceInstanceUpdateRequestBody.previousValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, serviceId, planId, parameters, previousValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInstanceUpdateRequestBody {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    previousValues: ").append(toIndentedString(previousValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
