/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Context;
import io.swagger.client.model.ServiceBindingResouceObject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ServiceBindingRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-26T00:20:45.219674+05:30[Asia/Kolkata]")
public class ServiceBindingRequest {
  @SerializedName("context")
  private Context context = null;

  @SerializedName("service_id")
  private String serviceId = null;

  @SerializedName("plan_id")
  private String planId = null;

  @SerializedName("app_guid")
  private String appGuid = null;

  @SerializedName("bind_resource")
  private ServiceBindingResouceObject bindResource = null;

  @SerializedName("parameters")
  private Object parameters = null;

  @SerializedName("predecessor_binding_id")
  private String predecessorBindingId = null;

  public ServiceBindingRequest context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }

  public ServiceBindingRequest serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @Schema(required = true, description = "")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public ServiceBindingRequest planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(required = true, description = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public ServiceBindingRequest appGuid(String appGuid) {
    this.appGuid = appGuid;
    return this;
  }

   /**
   * Get appGuid
   * @return appGuid
  **/
  @Schema(description = "")
  public String getAppGuid() {
    return appGuid;
  }

  public void setAppGuid(String appGuid) {
    this.appGuid = appGuid;
  }

  public ServiceBindingRequest bindResource(ServiceBindingResouceObject bindResource) {
    this.bindResource = bindResource;
    return this;
  }

   /**
   * Get bindResource
   * @return bindResource
  **/
  @Schema(description = "")
  public ServiceBindingResouceObject getBindResource() {
    return bindResource;
  }

  public void setBindResource(ServiceBindingResouceObject bindResource) {
    this.bindResource = bindResource;
  }

  public ServiceBindingRequest parameters(Object parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @Schema(description = "")
  public Object getParameters() {
    return parameters;
  }

  public void setParameters(Object parameters) {
    this.parameters = parameters;
  }

  public ServiceBindingRequest predecessorBindingId(String predecessorBindingId) {
    this.predecessorBindingId = predecessorBindingId;
    return this;
  }

   /**
   * Get predecessorBindingId
   * @return predecessorBindingId
  **/
  @Schema(description = "")
  public String getPredecessorBindingId() {
    return predecessorBindingId;
  }

  public void setPredecessorBindingId(String predecessorBindingId) {
    this.predecessorBindingId = predecessorBindingId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceBindingRequest serviceBindingRequest = (ServiceBindingRequest) o;
    return Objects.equals(this.context, serviceBindingRequest.context) &&
        Objects.equals(this.serviceId, serviceBindingRequest.serviceId) &&
        Objects.equals(this.planId, serviceBindingRequest.planId) &&
        Objects.equals(this.appGuid, serviceBindingRequest.appGuid) &&
        Objects.equals(this.bindResource, serviceBindingRequest.bindResource) &&
        Objects.equals(this.parameters, serviceBindingRequest.parameters) &&
        Objects.equals(this.predecessorBindingId, serviceBindingRequest.predecessorBindingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, serviceId, planId, appGuid, bindResource, parameters, predecessorBindingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceBindingRequest {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    appGuid: ").append(toIndentedString(appGuid)).append("\n");
    sb.append("    bindResource: ").append(toIndentedString(bindResource)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    predecessorBindingId: ").append(toIndentedString(predecessorBindingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
