/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Context;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ServiceInstanceProvisionRequestBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-26T00:20:45.219674+05:30[Asia/Kolkata]")
public class ServiceInstanceProvisionRequestBody {
  @SerializedName("service_id")
  private String serviceId = null;

  @SerializedName("plan_id")
  private String planId = null;

  @SerializedName("context")
  private Context context = null;

  @SerializedName("organization_guid")
  private String organizationGuid = null;

  @SerializedName("space_guid")
  private String spaceGuid = null;

  @SerializedName("parameters")
  private Object parameters = null;

  public ServiceInstanceProvisionRequestBody serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @Schema(required = true, description = "")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public ServiceInstanceProvisionRequestBody planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(required = true, description = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public ServiceInstanceProvisionRequestBody context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }

  public ServiceInstanceProvisionRequestBody organizationGuid(String organizationGuid) {
    this.organizationGuid = organizationGuid;
    return this;
  }

   /**
   * Get organizationGuid
   * @return organizationGuid
  **/
  @Schema(required = true, description = "")
  public String getOrganizationGuid() {
    return organizationGuid;
  }

  public void setOrganizationGuid(String organizationGuid) {
    this.organizationGuid = organizationGuid;
  }

  public ServiceInstanceProvisionRequestBody spaceGuid(String spaceGuid) {
    this.spaceGuid = spaceGuid;
    return this;
  }

   /**
   * Get spaceGuid
   * @return spaceGuid
  **/
  @Schema(required = true, description = "")
  public String getSpaceGuid() {
    return spaceGuid;
  }

  public void setSpaceGuid(String spaceGuid) {
    this.spaceGuid = spaceGuid;
  }

  public ServiceInstanceProvisionRequestBody parameters(Object parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @Schema(description = "")
  public Object getParameters() {
    return parameters;
  }

  public void setParameters(Object parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInstanceProvisionRequestBody serviceInstanceProvisionRequestBody = (ServiceInstanceProvisionRequestBody) o;
    return Objects.equals(this.serviceId, serviceInstanceProvisionRequestBody.serviceId) &&
        Objects.equals(this.planId, serviceInstanceProvisionRequestBody.planId) &&
        Objects.equals(this.context, serviceInstanceProvisionRequestBody.context) &&
        Objects.equals(this.organizationGuid, serviceInstanceProvisionRequestBody.organizationGuid) &&
        Objects.equals(this.spaceGuid, serviceInstanceProvisionRequestBody.spaceGuid) &&
        Objects.equals(this.parameters, serviceInstanceProvisionRequestBody.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceId, planId, context, organizationGuid, spaceGuid, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInstanceProvisionRequestBody {\n");
    
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    organizationGuid: ").append(toIndentedString(organizationGuid)).append("\n");
    sb.append("    spaceGuid: ").append(toIndentedString(spaceGuid)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
