/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ServiceInstanceSchemaCreate;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ServiceInstanceSchema
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-26T00:20:45.219674+05:30[Asia/Kolkata]")
public class ServiceInstanceSchema {
  @SerializedName("create")
  private ServiceInstanceSchemaCreate create = null;

  @SerializedName("update")
  private ServiceInstanceSchemaCreate update = null;

  public ServiceInstanceSchema create(ServiceInstanceSchemaCreate create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  @Schema(description = "")
  public ServiceInstanceSchemaCreate getCreate() {
    return create;
  }

  public void setCreate(ServiceInstanceSchemaCreate create) {
    this.create = create;
  }

  public ServiceInstanceSchema update(ServiceInstanceSchemaCreate update) {
    this.update = update;
    return this;
  }

   /**
   * Get update
   * @return update
  **/
  @Schema(description = "")
  public ServiceInstanceSchemaCreate getUpdate() {
    return update;
  }

  public void setUpdate(ServiceInstanceSchemaCreate update) {
    this.update = update;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInstanceSchema serviceInstanceSchema = (ServiceInstanceSchema) o;
    return Objects.equals(this.create, serviceInstanceSchema.create) &&
        Objects.equals(this.update, serviceInstanceSchema.update);
  }

  @Override
  public int hashCode() {
    return Objects.hash(create, update);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInstanceSchema {\n");
    
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
