/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Catalog;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CatalogApi
 */
@Ignore
public class CatalogApiTest {

    private final CatalogApi api = new CatalogApi();

    /**
     * get the catalog of services that the service broker offers
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void catalogGetTest() throws Exception {
        String xBrokerAPIVersion = null;
        Catalog response = api.catalogGet(xBrokerAPIVersion);

        // TODO: test validations
    }
}
