/*
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * OpenAPI spec version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AsyncOperation;
import io.swagger.client.model.Error;
import io.swagger.client.model.LastOperationResource;
import io.swagger.client.model.ServiceInstanceAsyncOperation;
import io.swagger.client.model.ServiceInstanceProvisionRequestBody;
import io.swagger.client.model.ServiceInstanceProvisionResponse;
import io.swagger.client.model.ServiceInstanceResource;
import io.swagger.client.model.ServiceInstanceUpdateRequestBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ServiceInstancesApi
 */
@Ignore
public class ServiceInstancesApiTest {

    private final ServiceInstancesApi api = new ServiceInstancesApi();

    /**
     * deprovision a service instance
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceInstanceDeprovisionTest() throws Exception {
        String xBrokerAPIVersion = null;
        String instanceId = null;
        String serviceId = null;
        String planId = null;
        String xBrokerAPIOriginatingIdentity = null;
        Boolean acceptsIncomplete = null;
        Object response = api.serviceInstanceDeprovision(xBrokerAPIVersion, instanceId, serviceId, planId, xBrokerAPIOriginatingIdentity, acceptsIncomplete);

        // TODO: test validations
    }
    /**
     * get a service instance
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceInstanceGetTest() throws Exception {
        String xBrokerAPIVersion = null;
        String instanceId = null;
        String xBrokerAPIOriginatingIdentity = null;
        String serviceId = null;
        String planId = null;
        ServiceInstanceResource response = api.serviceInstanceGet(xBrokerAPIVersion, instanceId, xBrokerAPIOriginatingIdentity, serviceId, planId);

        // TODO: test validations
    }
    /**
     * get the last requested operation state for service instance
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceInstanceLastOperationGetTest() throws Exception {
        String xBrokerAPIVersion = null;
        String instanceId = null;
        String serviceId = null;
        String planId = null;
        String operation = null;
        LastOperationResource response = api.serviceInstanceLastOperationGet(xBrokerAPIVersion, instanceId, serviceId, planId, operation);

        // TODO: test validations
    }
    /**
     * provision a service instance
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceInstanceProvisionTest() throws Exception {
        ServiceInstanceProvisionRequestBody body = null;
        String xBrokerAPIVersion = null;
        String instanceId = null;
        String xBrokerAPIOriginatingIdentity = null;
        Boolean acceptsIncomplete = null;
        ServiceInstanceProvisionResponse response = api.serviceInstanceProvision(body, xBrokerAPIVersion, instanceId, xBrokerAPIOriginatingIdentity, acceptsIncomplete);

        // TODO: test validations
    }
    /**
     * update a service instance
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceInstanceUpdateTest() throws Exception {
        ServiceInstanceUpdateRequestBody body = null;
        String xBrokerAPIVersion = null;
        String instanceId = null;
        String xBrokerAPIOriginatingIdentity = null;
        Boolean acceptsIncomplete = null;
        Object response = api.serviceInstanceUpdate(body, xBrokerAPIVersion, instanceId, xBrokerAPIOriginatingIdentity, acceptsIncomplete);

        // TODO: test validations
    }
}
